/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kltr;

/**
 *
 * @author ONE
 */
public class NewJFrame1 extends javax.swing.JFrame {

double num, ans;
int menghitung ;

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        hasil.setEnabled(false);
        jRadioButton1.setEnabled(true);
    
                                             
}
   
  public void total(){
      switch(menghitung){
          case 1:
              ans = num + Double.parseDouble(hasil.getText());
              hasil.setText(Double.toString(ans));
              break;
              
               case 2:
              ans = num - Double.parseDouble(hasil.getText());
              hasil.setText(Double.toString(ans));
              break;
              
               case 3:
              ans = num * Double.parseDouble(hasil.getText());
              hasil.setText(Double.toString(ans));
              break;
              
               case 4:
              ans = num / Double.parseDouble(hasil.getText());
              hasil.setText(Double.toString(ans));
              break;
              
                  case 5:
                      
              ans = num / Double.parseDouble(hasil.getText())*100/100;
              hasil.setText(Double.toString(ans));
              break;
                  
          
      }
      
  }   
     public void enable()
    { 
        hasil.setEnabled(true);
        
       tambah.setEnabled(true);
       kurang.setEnabled(true);
       bagi.setEnabled(true);
       kali.setEnabled(true);
       angka1.setEnabled(true);
       angka2 .setEnabled(true);
       angka3 .setEnabled(true);
        angka4.setEnabled(true);
        angka5.setEnabled(true);
        angka6.setEnabled(true);
       angka7.setEnabled(true);
        angka8.setEnabled(true);
        angka9.setEnabled(true);
        angka0.setEnabled(true);
        hapus.setEnabled(true);
        hapussemua.setEnabled(true);
        hasil.setEnabled(true);
        jButton1.setEnabled(true);
     
        jRadioButton1.setEnabled(true);
          jRadioButton2.setEnabled(true);
         titik.setEnabled(true);
            samadengan.setEnabled(true);
               label.setEnabled(true);
           
            
        
                
                
                    
       
    }
    public void disable()
    { 
        hasil.setEnabled(false);
        
       tambah.setEnabled(false);
       kurang.setEnabled(false);
       bagi.setEnabled(false);
       kali.setEnabled(false);
       angka1.setEnabled(false);
       angka2 .setEnabled(false);
       angka3 .setEnabled(false);
        angka4.setEnabled(false);
        angka5.setEnabled(false);
        angka6.setEnabled(false);
       angka7.setEnabled(false);
        angka8.setEnabled(false);
        angka9.setEnabled(false);
        angka0.setEnabled(false);
        hapus.setEnabled(false);
        hapussemua.setEnabled(false);
        hasil.setEnabled(false);
        jButton1.setEnabled(false);
        
        jRadioButton1.setEnabled(false);
          jRadioButton2.setEnabled(false);
         titik.setEnabled(false);
            samadengan.setEnabled(false);
          label.setEnabled(false);
             
        
                
                
                    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        hasil = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        hapussemua = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        angka0 = new javax.swing.JButton();
        angka9 = new javax.swing.JButton();
        angka8 = new javax.swing.JButton();
        angka7 = new javax.swing.JButton();
        angka4 = new javax.swing.JButton();
        angka5 = new javax.swing.JButton();
        angka6 = new javax.swing.JButton();
        angka3 = new javax.swing.JButton();
        angka2 = new javax.swing.JButton();
        angka1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        getContentPane().setLayout(null);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(30, 30, 320, 60);

        hapus.setBackground(new java.awt.Color(153, 153, 255));
        hapus.setText("C");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(130, 160, 60, 40);

        hapussemua.setBackground(new java.awt.Color(153, 153, 255));
        hapussemua.setText("←");
        hapussemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapussemuaActionPerformed(evt);
            }
        });
        getContentPane().add(hapussemua);
        hapussemua.setBounds(50, 160, 70, 40);

        bagi.setBackground(new java.awt.Color(153, 153, 255));
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(270, 260, 60, 40);

        kali.setBackground(new java.awt.Color(153, 153, 255));
        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(270, 160, 60, 40);

        kurang.setBackground(new java.awt.Color(153, 153, 255));
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang);
        kurang.setBounds(270, 210, 60, 40);

        tambah.setBackground(new java.awt.Color(153, 153, 255));
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(270, 310, 60, 40);

        samadengan.setBackground(new java.awt.Color(153, 153, 255));
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(samadengan);
        samadengan.setBounds(200, 360, 130, 40);

        titik.setBackground(new java.awt.Color(153, 153, 255));
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        getContentPane().add(titik);
        titik.setBounds(50, 360, 70, 40);

        angka0.setBackground(new java.awt.Color(153, 153, 255));
        angka0.setLabel("0");
        angka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka0ActionPerformed(evt);
            }
        });
        getContentPane().add(angka0);
        angka0.setBounds(130, 360, 60, 40);

        angka9.setBackground(new java.awt.Color(153, 153, 255));
        angka9.setText("9");
        angka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka9ActionPerformed(evt);
            }
        });
        getContentPane().add(angka9);
        angka9.setBounds(50, 210, 70, 40);

        angka8.setBackground(new java.awt.Color(153, 153, 255));
        angka8.setText("8");
        angka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka8ActionPerformed(evt);
            }
        });
        getContentPane().add(angka8);
        angka8.setBounds(130, 210, 60, 40);

        angka7.setBackground(new java.awt.Color(153, 153, 255));
        angka7.setText("7");
        angka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka7ActionPerformed(evt);
            }
        });
        getContentPane().add(angka7);
        angka7.setBounds(200, 210, 60, 40);

        angka4.setBackground(new java.awt.Color(153, 153, 255));
        angka4.setText("4");
        angka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka4ActionPerformed(evt);
            }
        });
        getContentPane().add(angka4);
        angka4.setBounds(200, 260, 60, 40);

        angka5.setBackground(new java.awt.Color(153, 153, 255));
        angka5.setText("5");
        angka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka5ActionPerformed(evt);
            }
        });
        getContentPane().add(angka5);
        angka5.setBounds(130, 260, 60, 40);

        angka6.setBackground(new java.awt.Color(153, 153, 255));
        angka6.setText("6");
        angka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka6ActionPerformed(evt);
            }
        });
        getContentPane().add(angka6);
        angka6.setBounds(50, 260, 70, 40);

        angka3.setBackground(new java.awt.Color(153, 153, 255));
        angka3.setText("3");
        angka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka3ActionPerformed(evt);
            }
        });
        getContentPane().add(angka3);
        angka3.setBounds(200, 310, 60, 40);

        angka2.setBackground(new java.awt.Color(153, 153, 255));
        angka2.setText("2");
        angka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka2ActionPerformed(evt);
            }
        });
        getContentPane().add(angka2);
        angka2.setBounds(130, 310, 60, 40);

        angka1.setBackground(new java.awt.Color(153, 153, 255));
        angka1.setText("1");
        angka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka1ActionPerformed(evt);
            }
        });
        getContentPane().add(angka1);
        angka1.setBounds(50, 310, 70, 40);

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(40, 110, 41, 23);

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(40, 130, 45, 23);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("%");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 160, 60, 40);

        jButton2.setBackground(new java.awt.Color(102, 51, 255));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 410, 170, 40);

        label.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(label);
        label.setBounds(20, 4, 160, 20);

        setSize(new java.awt.Dimension(380, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void angka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka2ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+"2");
        
    }//GEN-LAST:event_angka2ActionPerformed

    private void angka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka0ActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText()+"0");
       
    }//GEN-LAST:event_angka0ActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
total        ();
        
       
    }//GEN-LAST:event_samadenganActionPerformed

    private void angka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka1ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+ "1");
        
    }//GEN-LAST:event_angka1ActionPerformed

    private void angka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka3ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+"3");
        
    }//GEN-LAST:event_angka3ActionPerformed

    private void angka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka4ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+"4");
        
    }//GEN-LAST:event_angka4ActionPerformed

    private void angka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka5ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+"5");
        
    }//GEN-LAST:event_angka5ActionPerformed

    private void angka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka6ActionPerformed
        // TODO add your handling code here
         hasil.setText(hasil.getText()+"6");

    }//GEN-LAST:event_angka6ActionPerformed

    private void angka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka7ActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText()+"7");
    }//GEN-LAST:event_angka7ActionPerformed

    private void angka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka8ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+"8");
        
    }//GEN-LAST:event_angka8ActionPerformed

    private void angka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka9ActionPerformed
        // TODO add your handling code here:
         hasil.setText(hasil.getText()+"9");
       
    }//GEN-LAST:event_angka9ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
       hasil.setText("");
         
        
    }//GEN-LAST:event_hapusActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_hasilActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
       num = Double.parseDouble(hasil.getText());
       menghitung=1 ;
       hasil.setText("");
       label.setText(num +"+");
       
       
     
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
       num = Double.parseDouble(hasil.getText());
       menghitung= 2;
       hasil.setText("");
       label.setText(num +"-");
       
         
    }//GEN-LAST:event_kurangActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
         num = Double.parseDouble(hasil.getText());
       menghitung=4;
       hasil.setText("");
       label.setText(num +"/");
       
         
        
    }//GEN-LAST:event_bagiActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
          num = Double.parseDouble(hasil.getText());
       menghitung=3;
       hasil.setText("");
       label.setText(num +"*");
       
               
    }//GEN-LAST:event_kaliActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText()+".");
          
    }//GEN-LAST:event_titikActionPerformed

    private void hapussemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapussemuaActionPerformed
        // TODO add your handling code here:
        int lenght= hasil.getText().length();
        int number = hasil.getText().length()-1;
        String store;
        
        if (lenght>0)
        {
            StringBuilder back = new StringBuilder(hasil.getText());
            back.deleteCharAt(number);
            store=  back.toString();
            hasil.setText(store);
        }
    }//GEN-LAST:event_hapussemuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        num = Double.parseDouble (hasil.getText());
        menghitung = 5 ;
        hasil.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angka0;
    private javax.swing.JButton angka1;
    private javax.swing.JButton angka2;
    private javax.swing.JButton angka3;
    private javax.swing.JButton angka4;
    private javax.swing.JButton angka5;
    private javax.swing.JButton angka6;
    private javax.swing.JButton angka7;
    private javax.swing.JButton angka8;
    private javax.swing.JButton angka9;
    private javax.swing.JButton bagi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapussemua;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JLabel label;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
